edtech_platform/contacts/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views


app_name = 'contacts'

urlpatterns = [
    path('contacts/', views.ContactFormView.as_view(), name='contacts'),
    path('thanks/', TemplateView.as_view(template_name='contacts/thanks.html'), name='thanks'),
]

edtech_platform/courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.permissions import IsAuthenticated
from rest_framework.routers import DefaultRouter, APIRootView
from .views_api import TeacherViewSet, StudentViewSet, CourseViewSet, UserViewSet, CustomAPIRootView
from . import views

app_name = 'courses'


class CustomRouter(DefaultRouter):
    APIRootView = CustomAPIRootView


router = CustomRouter()
router.register("users", UserViewSet)
router.register("teachers", TeacherViewSet)
router.register("students", StudentViewSet)
router.register("courses", CourseViewSet)


urlpatterns = [
    path('', views.CoursesList.as_view(), name='index'),
    path('api/', include(router.urls)),

    path('about/', TemplateView.as_view(template_name='courses/about.html'), name='about'),

    path('course/<int:pk>/', views.CourseDetailView.as_view(), name='course'),

    path('course/create/', views.CourseCreateView.as_view(), name='course_create'),
    path('course/<int:pk>/update/', views.CourseUpdateView.as_view(), name='course_update'),
    path('course/<int:pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),

    path('test_fetch_axios/', TemplateView.as_view(template_name="courses/test_fetch_axios.html")),

]

edtech_platform/edtech_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from graphene_django.views import GraphQLView
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls', namespace='courses')),
    path('', include('contacts.urls', namespace='contacts')),
    path('api-auth/', include('rest_framework.urls')),
    path('auth-jwt/', include('jwtauthapp.urls')),
    path('graphql', GraphQLView.as_view(graphiql=True)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

urlpatterns += [
    path('django-rq/', include('django_rq.urls'))
]

edtech_platform/jwtauthapp/urls.py
from django.urls import path


from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

edtech_platform/contacts/models.py
from django.db import models

# Create your models here.

edtech_platform/courses/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Teacher(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.PROTECT)

    bio = models.TextField(default="", blank=True)

    def __str__(self):
        return f"Teacher <{self.user}>"


class Student(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.PROTECT)

    def __str__(self):
        return f"Student <{self.user}>"


class Course(models.Model):

    title = models.CharField(max_length=120, null=False, default="", blank=False)
    description = models.TextField(default="", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField(null=True, blank=True)
    edited_at = models.DateTimeField(auto_now=True)

    teachers = models.ManyToManyField(Teacher, related_name='courses')
    students = models.ManyToManyField(Student, null=True, blank=True, related_name='courses')

    def __str__(self):
        return f"Course {self.title!r}"

edtech_platform/jwtauthapp/models.py
from django.db import models

# Create your models here.

edtech_platform/contacts/forms.py
from django import forms


class ContactForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    subject = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

edtech_platform/contacts/views.py
from django.urls import reverse_lazy

from .forms import ContactForm
from django.views.generic.edit import FormView
import django_rq

from . import tasks
from . import config


class ContactFormView(FormView):
    template_name = 'contacts/contacts.html'
    form_class = ContactForm
    success_url = reverse_lazy('contacts:thanks')

    def form_valid(self, form):
        user_subject = form.cleaned_data['subject']
        user_text = form.cleaned_data['message']
        user_email = form.cleaned_data['email']

        subject_for_admin = config.SUBJECT_NOTIFICATION_PATTERN.format(user_subject)
        text_for_admin = config.TEXT_NOTIFICATION_PATTERN.format(user_email, user_subject, user_text)

        subject_for_user = config.SUBJECT_RESPONSE_PATTERN
        text_for_user = config.TEXT_RESPONSE_PATTERN.format(user_email, user_text)

        django_rq.enqueue(tasks.send_mail_task, subject_for_admin, text_for_admin, config.ADMIN_EMAIL, config.COMMON_EMAIL)
        django_rq.enqueue(tasks.send_mail_task, subject_for_user, text_for_user, user_email, config.COMMON_EMAIL)
        return super().form_valid(form)

edtech_platform/courses/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Course


class CoursesList(ListView):
    model = Course
    page_name = 'All Courses'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['page_name'] = self.page_name
        return context


class CourseDetailView(DetailView):
    model = Course
    page_name = 'Course details'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['page_name'] = self.page_name
        return context


class CourseCreateView(CreateView):
    model = Course
    page_name = 'Create new course'
    template_name_suffix = '_create'
    fields = ['title', 'description', 'teachers', 'students']
    success_url = reverse_lazy('courses:index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['page_name'] = self.page_name
        return context


class CourseDeleteView(DeleteView):
    model = Course
    page_name = 'Delete course'
    success_url = reverse_lazy('courses:index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['page_name'] = self.page_name
        return context


class CourseUpdateView(UpdateView):
    model = Course
    page_name = 'Edit course'
    template_name_suffix = '_update'
    fields = ['title', 'description', 'teachers', 'students']
    success_url = reverse_lazy('courses:index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['page_name'] = self.page_name
        return context

edtech_platform/jwtauthapp/views.py
from django.shortcuts import render

# Create your views here.

edtech_platform/contacts/templates/contacts/contacts.html
{% extends 'courses/base.html' %}

{% block container %}
    <h2>Contact us</h2>

{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form }}#}
{#        <input type="submit" value="Send">#}
{#    </form>#}
{#    #}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send message">
    </form>
{% endblock %}

edtech_platform/contacts/templates/contacts/thanks.html
{% extends 'courses/base.html' %}

{% block container %}
    <h2>Thank you for contacts us! <br>We will answer you as soon as possible!</h2>

{% endblock %}

edtech_platform/courses/templates/courses/about.html
{% extends 'courses/base.html' %}

{% block container %}
    <h2>About</h2>
    <p>The first platform with learning courses based information from top leaders of industries,
    well-known scientists and artists. Discover original books, science magazines articles,
    interviews and even tweets. Learn geometry by Euclid, quantum mechanics by Niels Bohr and Erwin Schrödinger,
    aerospace engineering by Elon Musk, crypto by Satoshi Nakamoto and Vitalik Buterin and many others. <p>

{% endblock %}

edtech_platform/courses/templates/courses/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {{ page_name|default:"Page"|title|add:" - Learn The Original"|title }}
    </title>
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>

{% block menu %}
    <div class="menu">
        <a href="{% url 'courses:index' %}">Main</a>
        <a href="{% url 'courses:about' %}">About</a>
        <a href="{% url 'contacts:contacts' %}">Contacts</a>
    </div>
{% endblock %}

{% block container %}
{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>

edtech_platform/courses/templates/courses/course_confirm_delete.html
{% extends 'courses/base.html' %}

{% block container %}

    <h3>{{ course.title }}</h3>
    <p>{{ course.description }}</p>

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Delete">
        <a href="{% url 'courses:index' %}">Cancel</a>
    </form>

{% endblock %}

edtech_platform/courses/templates/courses/course_create.html
{% extends 'courses/base.html' %}

{% block container %}

    <h3>New Course</h3>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
        <a href="{% url 'courses:index' %}">Cancel</a>
    </form>

{% endblock %}

edtech_platform/courses/templates/courses/course_detail.html
{% extends 'courses/base.html' %}

{% block container %}

    <h3>{{ object.title }}</h3>
    <p>{{ object.description }}</p>

    <a href="{% url 'courses:course_update' object.pk %}">Edit Course</a>
    <a href="{% url 'courses:course_delete' object.pk %}">Delete Course</a>

{% endblock %}

edtech_platform/courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}

{% block container %}

    {% include 'courses/incs/courses_list.html' %}

{% endblock %}

edtech_platform/courses/templates/courses/course_update.html
{% extends 'courses/base.html' %}

{% block container %}
    
    <h3>Edit Course</h3>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Edit">
        <a href="{% url 'courses:index' %}">Cancel</a>
    </form>

{% endblock %}

edtech_platform/courses/templates/courses/incs/courses_list.html
<div class="courses">
    <h1>Courses</h1>

    <ul>
        {% for item in object_list %}
            <li>
                <a href="{% url 'courses:course' item.pk %}">
                    {{ item.title }} ({{ item.created_at|date:"D d M Y" }})
                </a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'courses:course_create' %}">Create New Course</a>
</div>

edtech_platform/courses/templates/courses/test_fetch_axios.html
{% extends 'courses/base.html' %}

{% block container %}
    {% load static %}
    <script src="{% static 'frontend/index.js' %}"></script>
    <h1>Testing fetch and axios</h1>
{% endblock %}